version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    versioning-strategy: "widen"
    ignore:
      - dependency-name: "laravel/framework"